name: 'Markdown coverage report'
description: 'GitHub action for creating markdown coverage report from Istanbul text report'
author: 'FingerprintJS'
inputs:
  textReportPath:
    required: false
    description: 'path to the coverage report in Istanbul text format'
    default: './coverage/coverage.txt'
runs:
  using: 'node16'
  main: 'dist/index.js'
